---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 23341.
--- DateTime: 2024/10/14 16:46
---
---订单id  用户id
local voucherId = ARGV[1]
local userId = ARGV[2]
---库存 和 订单 key
local stockKey = 'seckill:stock:' .. voucherId
local orderKey = 'seckill:order:' .. voucherId
--- 库存不足时
if(tonumber(redis.call('get',stockKey)) <= 0 ) then
    return 1
end
---用户是否下过单
if(redis.call('sismember',orderKey,userId)==1) then
    return 2
end
---扣减库存
redis.call('incrby',stockKey,-1)
---下单
redis.call('sadd',orderKey,userId)
return 0