---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by 23341.
--- DateTime: 2024/10/11 22:20
---
if(redis.call('get', KEYS[1]) == ARGV[1])  then
    return redis.call('del',KEYS[1])
end
return 0